https://iamtrask.github.io/2015/07/12/basic-python-network/

In [1]:
import numpy as np

### Sigmoid Function

In [2]:
def nonlin(x, deriv=False):
    if deriv == True:
        return x*(1-x)
    return 1/(1+np.exp(-x))

### Input Dataset

In [3]:
x = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

### Output Dataset

In [4]:
y = np.array([[0, 0, 1, 1]]).T

### Seed Random Number to Make Calculations Deterministic

In [5]:
np.random.seed(1)

### Initialize Weights Randomly with Mean 0

In [ ]:
syn0 = 2*np.random.random((3,1)) - 1

In [ ]:
for iterable in range(10000):
    print("round: ", iterable)
    print("\n\nsyn0 at start: \n", syn0)
    # forward propegation
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    print("\n\nl0:\n", l0, "\n\nl1:\n", l1)
    
    # how much did we miss
    l1_error = y - l1
    print("\n\nl1_error:\n", l1_error)
    
    # multiply how much we missed by the slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    print("\n\nl1_delta:\n", l1_delta)
    
    #update weights
    syn0 += np.dot(l0.T, l1_delta)
    print("\n\nsyn0 at end: \n", syn0)
    
print("\n\nOutput after training:\n", l1)

round:  0


syn0 at start: 
 [[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


l0:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] 

l1:
 [[ 0.2689864 ]
 [ 0.36375058]
 [ 0.23762817]
 [ 0.3262757 ]]


l1_error:
 [[-0.2689864 ]
 [-0.36375058]
 [ 0.76237183]
 [ 0.6737243 ]]


l1_delta:
 [[-0.05289153]
 [-0.08418501]
 [ 0.13811206]
 [ 0.14809799]]


syn0 at end: 
 [[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]
round:  1


syn0 at start: 
 [[ 0.12025406]
 [ 0.50456196]
 [-0.85063774]]


l0:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] 

l1:
 [[ 0.29929909]
 [ 0.41433436]
 [ 0.32511054]
 [ 0.44378327]]


l1_error:
 [[-0.29929909]
 [-0.41433436]
 [ 0.67488946]
 [ 0.55621673]]


l1_delta:
 [[-0.06276875]
 [-0.10054295]
 [ 0.14807998]
 [ 0.13729636]]


syn0 at end: 
 [[ 0.40563039]
 [ 0.54131537]
 [-0.72857311]]
round:  2


syn0 at start: 
 [[ 0.40563039]
 [ 0.54131537]
 [-0.72857311]]


l0:
 [[0 0 1]
 [0 1 1]
 [1 0 1]
 [1 1 1]] 

l1:
 [[ 0.32550793]
 [ 0.45332188]
 [ 0.41995875]
 [ 0.55437725]]


l1_error:
 [[-0

# Layer Neural Network

### Input Dataset

In [ ]:
x = np.array([[0, 0, 1],
              [0, 1, 1],
              [1, 0, 1],
              [1, 1, 1]])

### Output Dataset

In [ ]:
y = np.array([[0],
              [1],
              [1],
              [0]])

### Seed Random Number to Make Calculations Deterministic

In [ ]:
np.random.seed(1)

### Random Initialize Our Weight with Mean 0

In [ ]:
syn0 = 2*np.random.random((3, 4)) - 1
syn1 = 2*np.random.random((4, 1)) - 1

In [ ]:
for iterable in range (60000):
    # Feed forward through layers 0, 1, and 2.
    l0 = x
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # How much did we miss the target value?
    l2_error = y - l2
    
    if (iterable % 10000) == 0:
        print("Error: " + str(np.mean(np.abs(l2_error))))
    
    # In what direction is the target value? Were we really sure? if so, don't change much.
    l2_delta = l2_error * nonlin(l2, deriv=True)
    
    # How much did each l1 value contribute to l2 error (according to weights)?
    l1_error = l2_delta.dot(syn1.T)
    
    # In what direction is the target l1? Were we really sure? if so don't change much.
    l1_delta = l1_error * nonlin(l2, deriv=True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)